=== HassanNadeemWebD/2202B1/XML/my.dtd
<!ELEMENT Emails (A:Email , B:Email)>
<!ELEMENT A:Email (A:To, A:From, A:Subject, A:Body)>
<!ELEMENT A:To (#PCDATA)>
<!ELEMENT A:From (#PCDATA)>
<!ELEMENT A:Subject (#PCDATA)>
<!ELEMENT A:Body (#PCDATA)>
<!ELEMENT B:Email (B:To, B:From, B:Subject, B:Body)>
<!ELEMENT B:To (#PCDATA)>
<!ELEMENT B:From (#PCDATA)>
<!ELEMENT B:Subject (#PCDATA)>
<!ELEMENT B:Body (#PCDATA)>
<!ELEMENT email (To, From, Subject, Body, Greetings,Date)>
<!ATTLIST A:To center CDATA #REQUIRED>
<!ATTLIST A:From name CDATA #IMPLIED>
<!ATTLIST A:Body content CDATA "mycontent">
<!ATTLIST A:Subject topic (leave|tour|increment) "leave">
<!ATTLIST B:To center CDATA #REQUIRED>
<!ATTLIST B:From name CDATA #IMPLIED>
<!ATTLIST B:Body content CDATA "mycontent">
<!ATTLIST B:Subject topic (leave|tour|increment) "leave">
<!ATTLIST Emails xmlns:A CDATA "https://www.yahoo.com">
<!ATTLIST Emails xmlns:B CDATA "https://www.gmail.com">
<!ELEMENT Greetings (#PCDATA)>
<!ELEMENT Date (#PCDATA)>

=== HassanNadeemWebD/2202B1/XML/index.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE Emails SYSTEM "my.dtd" [


<!ENTITY North "Aptech North">
<!ENTITY South "Aptech South">

]>


<Emails xmlns:A="https://www.yahoo.com" xmlns:B="https://www.gmail.com">


    <A:Email>

        <A:To center="aptech"> Sir Bilal </A:To>
        <A:From name="abc">Sir Hassan</A:From>
        <A:Subject topic="increment">Leave Request  </A:Subject>
        <A:Body></A:Body>


    </A:Email>
    <B:Email>

        <B:To center="aptech"> Sir Haris </B:To>
        <B:From name="abc">Sir Hassan</B:From>
        <B:Subject topic="increment">Leave Request</B:Subject>
        <B:Body content="para">They are my entities </B:Body>


</B:Email>
    <!-- <email>
        <To center="aptech"> Sir Bilal </To>
        <From name="abc">Sir Hassan</From>
        <Subject topic="increment">Leave Request</Subject>
        <Body>Hello! This is my email body</Body>
        <Greetings>Thanks</Greetings>
        <Date>20-Aug-2022</Date>
    </email> -->


</Emails>
